AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template for deploying the 'tank-game' app to Elastic Beanstalk.

Parameters:
  EnvironmentName:
    Type: String
    Description: A name for the Elastic Beanstalk environment.
  S3Bucket:
    Type: String
    Description: The S3 bucket containing the zipped application code.
  S3Key:
    Type: String
    Description: The S3 key of the zipped application code.

Resources:
  TankGameApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: "tank-game"
      Description: "Elastic Beanstalk Application for the Tank Game Node.js app"

  TankGameApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref TankGameApplication
      SourceBundle:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key

  TankGameInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref TankGameInstanceRole

  TankGameInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier"
        - "arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker"
        - "arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier"

  TankGameEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref TankGameApplication
      EnvironmentName: !Ref EnvironmentName
      SolutionStackName: "64bit Amazon Linux 2023 v6.0.4 running Node.js 18"
      VersionLabel: !Ref TankGameApplicationVersion
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t2.micro
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref TankGameInstanceProfile

Outputs:
  ApplicationURL:
    Description: URL of the Elastic Beanstalk Environment
    Value: !GetAtt [TankGameEnvironment, EndpointURL]
